### ISSUE TITLE
简体中文版

### ISSUE THREAD

**Issue by ShadowRZ** [clarkzjw/Error451-Blackout#1]
我可以做简体中文版吗？

**Comment by clarkzjw** [comment]
@ShadowRZ 当然可以啦 😄

**Comment by ShadowRZ** [comment]
在做，不过手机的FireFox在编辑过程中崩溃了，已报告Mozilla

**Comment by ShadowRZ** [comment]
https://github.com/ShadowRZ/Error451-Blackout/tree/zh-CN-dev

**Comment by ShadowRZ** [comment]
一会提交

**Comment by ShadowRZ** [comment]
@clarkzjw 还在吗？
https://github.com/ShadowRZ/Error451-Blackout/tree/zh-CN-dev

**Comment by clarkzjw** [comment]
@ShadowRZ OK，你如果方便的话提一个Pull Request吧。如果不方便的话我手动把你的代码合过来。

**Comment by ShadowRZ** [comment]
@clarkzjw Pull Request已创建
https://github.com/ShadowRZ/Error451-Blackout/pull/1

**Comment by clarkzjw** [comment]
@ShadowRZ Hello，你现在是在自己的repo创建的pr。你应该在自己的repo下面把zh-CN-dev分支合并之后，再发一个pr到我的这个repo里面。

**Comment by ShadowRZ** [comment]
可以

**Comment by ShadowRZ** [comment]
@clarkzjw PR在这里：
https://github.com/clarkzjw/Error451-Blackout/pull/2

**Comment by ShadowRZ** [comment]
按照commit https://github.com/clarkzjw/Error451-Blackout/commit/a2ee43a00e7d9326783409a30202dabe599e48c4 和commit https://github.com/clarkzjw/Error451-Blackout/commit/d175cb10def43d13e9abb6ae1f84ba8ab9027e75 ，本issue关闭。

**Comment by ShadowRZ** [comment]
对了，还有 https://github.com/clarkzjw/Error451-Blackout/commit/be95775420f69d221f7bb83f587bea18da886e21
