### ISSUE TITLE
discuss

### ISSUE THREAD

**Issue by ghost** [clarkzjw/Error451-Blackout#3]
您好！
我刚刚测试过，手机chrome正常访问
不过，这个页面还有一点瑕疵
能否把弹窗图片改成浮动显示，图片边缘有一点儿阴影，像这样：
![cardm_search](https://cloud.githubusercontent.com/assets/25820917/23023230/7da13dc8-f48f-11e6-8bbf-ed39628ca20f.PNG)
图片的出现可用渐变效果，同时四周变暗，点击图片外面区域实现返回，手机俩手指放图片上可实现放大且背景页面大小不变
若能实现上述条件，这个页面堪称完美

以上只是我个人的看法，总觉得弹窗显示太low了~~

**Comment by clarkzjw** [comment]
感谢关注🙏
但我也是一个前端苦手，并不是专业的前端啦（。如果您熟悉前端的话，欢迎提pr :smile: 
Get Outlook for iOS




On Thu, Feb 16, 2017 at 9:39 PM +0800, "无可奉告" <notifications@github.com> wrote:












您好！

我刚刚测试过，手机chrome正常访问

不过，这个页面还有一点瑕疵

能否把弹窗图片改成浮动显示，图片边缘有一点儿阴影，像这样：



图片的出现可用渐变效果，同时四周变暗，点击图片外面区域实现返回，手机俩手指放图片上可实现放大且背景页面大小不变

若能实现上述条件，这个页面堪称完美


以上只是我个人的看法，总觉得弹窗显示太low了~

**Comment by wukefengao** [comment]
http://www.lanrentuku.com/js/tupian.html 这里有些代码可以参考的，我想想怎么做吧

**Comment by ShadowRZ** [comment]
我也会试着去做的。
ShadowRZ/Error451-Blackout#5

**Comment by ShadowRZ** [comment]
其实可以从0开始写这个代码。
~~Re: 从零开始的JS生活~~

**Comment by ShadowRZ** [comment]
@wukefengao @clarkzjw
可以使用CSS3制作这些效果。
我的方案是：
创建铺满浏览器页面的元素，
在其之上创建图片元素，
用CSS3和JS动态添加圆角和阴影。

**Comment by ShadowRZ** [comment]
@wukefengao @clarkzjw 
请确定圆角大小及阴影偏移位置加上模糊距离。
（为何默认分支改为rm?）

**Comment by clarkzjw** [comment]
你可以先定参数做一个demo出来看看再说，无妨

Get Outlook for iOS




On Sat, Feb 18, 2017 at 8:34 PM +0800, "Mu Yuxuan" <notifications@github.com> wrote:












@wukefengao @clarkzjw

请确定圆角大小及阴影偏移位置加上模糊距离。

（为何默认分支改为rm?）

**Comment by ShadowRZ** [comment]
@clarkzjw 可以做一个单独的JS库实现这些功能，然后用Github Pages做预览，这样可以手动确定。

**Comment by wukefengao** [comment]
https://ishadow.co/ 这个网站，点击windows使用教程会有一个页面覆盖上去，可以参考这个设计，然后覆盖在上层的页面可以把背景改为透明毛玻璃效果，然后在这个页面防那张zhao的图片。各位觉得如何？

**Comment by ShadowRZ** [comment]
https://github.com/ShadowRZ/floatimg-js 欢迎支持~
